### PR TITLE
Prepare the 0.3.0 release.

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by dsheets** [comment]
This may need some more changelog entries?

**Comment by yallop** [comment]
What do you have in mind?

**Comment by dsheets** [comment]
`Fcntl_unix`, `Fcntl_unix_lwt`? Maybe we should call `Fcntl_unix_lwt` just `Fcntl_lwt` because the data types and conversions alone will never have reason to use lwt without a system for I/O?

**Comment by yallop** [comment]
`Fcntl_unix` was [in 0.2.0](https://github.com/dsheets/ocaml-unix-fcntl/blob/0.2.0/lib/fcntl_unix.mli).  The `lwt` binding is [already mentioned](https://github.com/yallop/ocaml-unix-fcntl/blob/d82d742bd499dd9ae2c6f51a4e660c7e6ae5f631/CHANGES#L4), but I'll add a reference to the module.

I don't have strong views about the name `Fcntl_unix_lwt`.  I think the `_unix_lwt` suffix indicates that it's more closely related to `Fcntl_unix` than to `Fcntl`, and that it won't be available on non-Unix systems, even those (such as `js_of_ocaml`) that support `lwt`, but I'll rename it if you prefer; let me know either way.

**Comment by dsheets** [comment]
No, that all makes sense, thanks!

**Pull request merged**
